### PR TITLE
Added COC and Contributing

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
cc @imanishbarnwal

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
I have added Code of Conduct and Contributing, which is a very important aspect for an opensource project.

**Comment by imanishbarnwal** [comment]
Is there any issue related to this? Tag the issue please

**Comment by MrKrishnaAgarwal** [comment]
Should I make a issue referencing this PR?

**Comment by MrKrishnaAgarwal** [comment]
closes #28

**Comment by MrKrishnaAgarwal** [comment]
Screenshots for ref:

image

image

**Comment by imanishbarnwal** [comment]
Thanks

**Comment by MrKrishnaAgarwal** [comment]
Thanks @imanishbarnwal, can you add `hacktoberfest-accepted` label
so that my contribution will count.

**Comment by MrKrishnaAgarwal** [comment]
Closes #29

**Comment by imanishbarnwal** [comment]
not required if it's accepted

**Comment by MrKrishnaAgarwal** [comment]
> not required if it's accepted

Ohh...Okay
Thanks

**Pull request merged**
