### PR TITLE
Make contact linked

### PR DESCRIPTION
**Pull request by developer-diganta**
#52 
I have made the email and address linked to their apps.

### CODE REVIEW

**Comment by imanishbarnwal** [comment]
Can you please drop a screenshot that how it looks after adding icon

**Comment by developer-diganta** [comment]
Sure! Here it is
image

**Comment by imanishbarnwal** [comment]
Hi, @developer-diganta can you please remove this `:` after icon that will look better I guess.

**Comment by imanishbarnwal** [comment]
Yes yes, but I think previous one looks better. What do you think?

**Comment by developer-diganta** [comment]
Yeah. I was also thinking the first one looks better.

**Comment by imanishbarnwal** [comment]
Merged thanks

**Pull request merged**
