### PR TITLE
Fix created About Us page

### PR DESCRIPTION
**Pull request by amanchoudhary18**
Add-
• New About us page with vision, mission and teams

Fix-
•  Linking to new about us page.

### CODE REVIEW

**Comment by imanishbarnwal** [comment]
Can you please drop some screenshots that how it looks now?

**Comment by amanchoudhary18** [comment]
image
image
image

**Comment by imanishbarnwal** [comment]
Hi I guess there is some merge conflicts here kindly fix this

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
@amanchoudhary18 Kindly fix merge conflicts

**Pull request closed without merging**
