### PR TITLE
added hover function in the speaker class of event page 

### PR DESCRIPTION
**Pull request by randhirshaw**
hover

hope you will accept.

If any changes required in design then also tell me about that ASAP!!!!

### CODE REVIEW

**Comment by imanishbarnwal** [comment]
Hi @randhirshaw, we are planning to shift all these into an archive page if you would like to help us with those here's issue #19 let me know if you want to work on that.

**Comment by randhirshaw** [comment]
okay thanks @imanishbarnwal , I can work on issue #19 but need more clear information like name of archive page and in teams there are leads oragnisers, team leads, core team so do I have to move whole teams in archives or specific teams etc also I can't see the no. of registration in previous year. !!

**Comment by imanishbarnwal** [comment]
Yes, in the menu bar you can create a **More** --> **Season 1** page where all these details will be there and put the whole team details. And about registration data here you go `Applications: 2000+`, `Submitted: 1557`, `Teams: 175`, `Individuals: 618`, `Submission: 307` I hope this will help. Let me know if you need anything else.

**Comment by randhirshaw** [comment]
Still could'nt find it Applications: 2000+, Submitted: 1557, Teams: 175, Individuals: 618, Submission: 307  on  https://hack4bengal.tech/

are you talking about this?
are you talking about this

**Comment by imanishbarnwal** [comment]
No no it's not there we need to create this one in archive page.

**Comment by randhirshaw** [comment]
as event page is not mentioned in the archive document and i guess it is not affecting the other parts, so accept this PR by checking it thoroughly. and gonna add archive page in diffrent PR.

**Comment by randhirshaw** [comment]
okay got it now!! by mistakenly i clicked on close with comment😅

**Comment by imanishbarnwal** [comment]
Yes we can close this one and do further discussion on #19 issue

**Pull request closed without merging**
