### PR TITLE
added greetings workflow 

### LINKED ISSUE #34: Greetings
I will add a github action which greets user whenever someone makes a PR or Issue by posting a comment.

Can I @imanishbarnwal?

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
closes #34 

@imanishbarnwal

### CODE REVIEW

**Comment by imanishbarnwal** [comment]
Hi @MrKrishnaAgarwal are you still working on this?

**Comment by MrKrishnaAgarwal** [comment]
yes

**Comment by MrKrishnaAgarwal** [comment]
see my pr

**Comment by imanishbarnwal** [comment]
> yes

Kindly do the necessary changes as mentioned.

**Comment by MrKrishnaAgarwal** [comment]
what are the necessary changes as mentioned??
@imanishbarnwal

**Comment by MrKrishnaAgarwal** [comment]
I can't see anything

**Review by imanishbarnwal — CHANGES_REQUESTED** [review]
What is Nouv??? Ig you copy-pasted from somewhere and forgot to change. Do update this to `Hack4Bengal`.

**Comment by imanishbarnwal** [comment]
Check now @MrKrishnaAgarwal can you see?

**Comment by MrKrishnaAgarwal** [comment]
@imanishbarnwal I never do copy paste, and if i copy paste, I give credits.

and i have made requested changes

**Pull request merged**
