### PR TITLE
added self-assign workflow

### LINKED ISSUE #32: Allow contributors to self-assign issues with GitHub workflow
Commenting `#self-assign` or `take` in any issue will let repository members to self-assign that issue to themselves.

👉 This reduces chores for repo-maintainer(s).

cc @imanishbarnwal 

Can I work on this issue and make a PR?

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
Closes #32 

cc @imanishbarnwal

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
I am showing example below here by commenting `self-assign`

**Comment by MrKrishnaAgarwal** [comment]
#self-assign

**Comment by MrKrishnaAgarwal** [comment]
Demo: https://github.com/MrKrishnaAgarwal/hack4bengal.github.io/issues/2

image

**Comment by MrKrishnaAgarwal** [comment]
**It's a very helpful workflow @imanishbarnwal
Please review this PR**

**Comment by imanishbarnwal** [comment]
I don't think it's required for this repo as it's a very small project and we want this to be reviewed manually. So, thanks for the suggesstion.

**Comment by MrKrishnaAgarwal** [comment]
> I don't think it's required for this repo as it's a very small project and we want this to be reviewed manually. So, thanks for the suggestion.

Should I close the PR then?

**Comment by imanishbarnwal** [comment]
I am doing, thanks

**Pull request closed without merging**
