### PR TITLE
Changed the css of scrollbar

### PR DESCRIPTION
**Pull request by developer-diganta**
#48 
I have changed the styling of the scroll bar CSS. Is it OK? Or is there any other color set?
image

### CODE REVIEW

**Comment by imanishbarnwal** [comment]
Hey, I guess there are some merge conflicts. Kindly fix them.

**Comment by developer-diganta** [comment]
Done! Can you please check once?

**Comment by imanishbarnwal** [comment]
Hey also requested to change the color using this hex code `#FF1717` :)

**Comment by developer-diganta** [comment]
Sure!

**Pull request merged**
