### PR TITLE
Update all ids

### PR DESCRIPTION
**Pull request by Susmita-Dey**
Closes issue #46 

I have updated all ids of all pages from `services` to `themes` and `portfolio` to sponsors.

I have checked locally that there are no broken changes to the website and everything is working fine.

Kindly review and merge this PR.

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
Updated the branch and fixed merged conflicts

**Comment by imanishbarnwal** [comment]
Hi @Susmita-Dey it's kind of a big and sensitive change. So have you checked all features or options working properly?

**Comment by Susmita-Dey** [comment]
> Hi @Susmita-Dey it's kind of a big and sensitive change. So have you checked all features or options working properly?

Yes, I have taken care of every part of the website. Being a web developer I understand how sensitive things are. 

I'd suggest to host it wither on vercel or netlify so that you can check deploy-preview before merging any PR.

For now, you can merge this PR

**Comment by imanishbarnwal** [comment]
Cool, also we would love to have you in our Hack4Bengal web team soon will schedule a call with you if you are interested. Thanks for your contribution ✨

**Pull request merged**
