### PR TITLE
Made separate files for js and css

### PR DESCRIPTION
**Pull request by Susmita-Dey**
Closes issue #47 

- [x] Non breaking changes to the website
- [x] Formatted code

Kindly review and merge this PR.

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
Updated the branch and fixed merged conflicts

**Comment by imanishbarnwal** [comment]
Thanks @Susmita-Dey

**Comment by imanishbarnwal** [comment]
Oops I guess there are merge conflicts @Susmita-Dey check this once.

**Comment by Susmita-Dey** [comment]
> Oops I guess there are merge conflicts @Susmita-Dey check this once.

Fixed

**Comment by Susmita-Dey** [comment]
Website is up and running properly. 🚀

**Pull request merged**
